// app/admin/produtos/styles.ts
import React from "react";

export const styles: { [key: string]: React.CSSProperties } = {
  page: { display: 'flex', height: '100vh', width: '100%', maxWidth: '100vw', background: '#f8fafc', overflow: 'hidden', boxSizing: 'border-box', position: 'relative' },
  modalOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.5)', display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 1000 },
  modalContent: { background: '#fff', padding: '20px', borderRadius: '12px', width: '80%', maxWidth: '600px', height: '70vh', display: 'flex', flexDirection: 'column' },
  modalTextarea: { flex: 1, padding: '15px', borderRadius: '8px', border: '1px solid #e2e8f0', fontSize: '14px', resize: 'none', lineHeight: '1.5' },
  sidebar: { width: '260px', minWidth: '260px', maxWidth: '260px', background: '#fff', padding: '15px', overflowY: 'auto', borderRight: '1px solid #e2e8f0', boxSizing: 'border-box' },
  main: { flex: 1, padding: '15px', overflowY: 'auto', overflowX: 'hidden', boxSizing: 'border-box' },
  topHeader: { display: 'flex', flexDirection: 'column', gap: '10px', marginBottom: '15px', width: '100%', boxSizing: 'border-box' },
  filterRow: { display: 'flex', gap: '5px', alignItems: 'center', width: '100%', boxSizing: 'border-box' },
  searchBar: { flex: 3, padding: '10px', borderRadius: '8px', border: '1px solid #e2e8f0', fontSize: '13px' },
  selectTop: { flex: 1, padding: '10px', borderRadius: '8px', border: '1px solid #e2e8f0', background: '#fff', fontSize: '13px' },
  selectStatus: { width: '100px', padding: '10px', borderRadius: '8px', border: '1px solid #e2e8f0', background: '#fff' },
  btnGeneric: { padding: '10px 15px', borderRadius: '8px', border: '1px solid #e2e8f0', fontWeight: 'bold', cursor: 'pointer', fontSize: '12px' },
  massPanel: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: '#eff6ff', padding: '10px', borderRadius: '10px', border: '1px solid #3b82f6' },
  btnMass: { padding: '6px 12px', background: '#fff', border: '1px solid #3b82f6', borderRadius: '6px', fontSize: '11px', fontWeight: 'bold', cursor: 'pointer' },
  productGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(145px, 1fr))', gap: '10px', width: '100%' },
  card: { background: '#fff', borderRadius: '10px', border: '1px solid #e2e8f0', position: 'relative', overflow: 'hidden', boxSizing: 'border-box', display: 'flex', flexDirection: 'column', height: 'auto', minHeight: '280px', paddingBottom: '5px' },
  starBadge: { position: 'absolute', top: '5px', right: '5px', zIndex: 5, fontSize: '14px' },
  cardCheck: { position: 'absolute', top: '8px', left: '8px', zIndex: 10, width: '18px', height: '18px' },
  cardImg: { width: '100%', height: '100px', minHeight: '100px', maxHeight: '100px', objectFit: 'contain', background: '#ffffff', padding: '4px', display: 'block', borderBottom: '1px solid #f1f5f9', boxSizing: 'border-box' },
  cardBody: { padding: '8px', display: 'flex', flexDirection: 'column', flex: 1, justifyContent: 'flex-start', gap: '2px' },
  cardTitle: { fontSize: '10px', fontWeight: 'bold', height: '24px', color: '#334155', overflow: 'hidden', display: '-webkit-box', WebkitLineClamp: 2, WebkitBoxOrient: 'vertical', lineHeight: '12px', marginBottom: '4px' },
  cardPrice: { fontSize: '13px', fontWeight: 'bold', color: '#10b981', marginTop: 'auto' },
  markupTag: { fontSize: '9px', background: '#ecfdf5', color: '#059669', padding: '1px 4px', borderRadius: '4px', fontWeight: '800', alignSelf: 'flex-start' },
  cardActions: { display: 'flex', flexDirection: 'column', gap: '4px', marginTop: 'auto', padding: '0 8px 8px 8px' },
  btnSlim: { padding: '4px', fontSize: '9px', fontWeight: 'bold', border: 'none', borderRadius: '3px', background: '#f1f5f9', cursor: 'pointer', textAlign: 'center' },
  btnDelete: { padding: '4px', fontSize: '9px', fontWeight: 'bold', border: 'none', borderRadius: '3px', background: '#fef2f2', color: '#ef4444', cursor: 'pointer', textAlign: 'center' },
  sideTitle: { fontSize: '15px', fontWeight: 'bold', marginBottom: '15px' },
  input: { width: '100%', padding: '10px', borderRadius: '8px', border: '1px solid #e2e8f0', marginBottom: '10px', fontSize: '13px', boxSizing: 'border-box' },
  textarea: { width: '100%', height: '80px', padding: '10px', borderRadius: '8px', border: '1px solid #e2e8f0', marginBottom: '10px', fontSize: '13px', boxSizing: 'border-box', resize: 'none', overflow: 'hidden' },
  freteBox: { padding: '10px', background: '#eff6ff', borderRadius: '8px', marginBottom: '10px', border: '1px solid #dbeafe' },
  checkLabel: { fontSize: '12px', fontWeight: 'bold', display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer' },
  boxGray: { background: '#f1f5f9', padding: '10px', borderRadius: '8px', marginBottom: '10px' },
  miniLabel: { fontSize: '11px', fontWeight: 'bold', color: '#64748b', display: 'block', marginBottom: '5px' },
  grid2: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '5px' },
  inputSmall: { width: '100%', padding: '8px', fontSize: '12px', borderRadius: '6px', border: '1px solid #cbd5e1', boxSizing: 'border-box' },
  btnSave: { width: '100%', padding: '14px', background: '#10b981', color: '#fff', border: 'none', borderRadius: '8px', fontWeight: 'bold', cursor: 'pointer', marginTop: '10px' },
  btnCancel: { width: '100%', marginTop: '5px', padding: '10px', background: '#f1f5f9', border: 'none', borderRadius: '8px', fontSize: '12px', cursor: 'pointer' },
  btnUpload: { width: '100%', padding: '12px', background: '#f8fafc', border: '1px dashed #cbd5e1', borderRadius: '8px', cursor: 'pointer', marginBottom: '10px', position: 'relative', fontSize: '12px' },
  btnConfirmImgs: { width: '100%', padding: '8px', background: '#3b82f6', color: '#fff', border: 'none', borderRadius: '6px', fontSize: '11px', marginBottom: '10px', cursor: 'pointer' },
  fileInvis: { position: 'absolute', inset: 0, opacity: 0, cursor: 'pointer' },
  previewGrid: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '4px', marginBottom: '10px' },
  imgThumb: { width: '100%', height: '40px', objectFit: 'cover', borderRadius: '4px' },
  btnDelImg: { position: 'absolute', top: -5, right: -5, background: '#ef4444', color: '#fff', border: 'none', borderRadius: '50%', width: '18px', height: '18px', fontSize: '10px' },
  catManager: { background: '#f8fafc', padding: '8px', borderRadius: '8px', marginBottom: '10px', border: '1px solid #e2e8f0' },
  catItem: { display: 'flex', justifyContent: 'space-between', marginBottom: '4px', fontSize: '11px', alignItems: 'center' },
  btnAddCat: { width: '100%', padding: '5px', fontSize: '10px', background: '#fff', border: '1px solid #cbd5e1', borderRadius: '4px', cursor: 'pointer' },
  btnActionSmall: { padding: '10px', background: '#fff', border: '1px solid #e2e8f0', borderRadius: '8px', cursor: 'pointer' },
  btnMini: { border: 'none', background: 'none', cursor: 'pointer', fontSize: '10px' },
  planCard: { padding: '12px', background: '#f8fafc', borderRadius: '10px', marginBottom: '15px', border: '1px solid #e2e8f0' },
  planTitle: { fontSize: '11px', margin: '0 0 8px 0', color: '#64748b', fontWeight: 'bold', textTransform: 'uppercase' },
  planStats: { display: 'flex', justifyContent: 'space-between', fontSize: '12px', marginBottom: '4px', fontWeight: '500' },
  progressBarBg: { width: '100%', height: '6px', background: '#e2e8f0', borderRadius: '10px', overflow: 'hidden' },
  progressBarFill: { height: '100%', transition: '0.3s' }
};

export const shopeeStyles: { [key: string]: React.CSSProperties } = {
  overlay: { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.6)', zIndex: 2000, display: 'flex', alignItems: 'center', justifyContent: 'center' },
  modal: { background: '#fff', width: '95%', maxWidth: '800px', height: '90vh', borderRadius: '4px', display: 'flex', flexDirection: 'column' },
  header: { padding: '15px 20px', borderBottom: '1px solid #e8e8e8', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  title: { fontSize: '18px', margin: 0, color: '#333333' },
  closeBtn: { border: 'none', background: 'none', fontSize: '20px', cursor: 'pointer', color: '#f50c0c' },
  content: { flex: 1, overflowY: 'auto', padding: '20px' },
  section: { marginBottom: '25px' },
  label: { display: 'block', marginBottom: '10px', fontWeight: 'bold', color: '#494646' },
  varBox: { border: '1px solid #e8e8e8', padding: '15px', borderRadius: '2px', background: '#fafafa' },
  tagsContainer: { display: 'flex', flexWrap: 'wrap', gap: '8px', marginTop: '10px' },
  tagInputWrapper: { display: 'flex', alignItems: 'center', background: '#fff', border: '1px solid #dcdcdc', borderRadius: '2px' },
  tagInput: { border: 'none', padding: '6px 10px', outline: 'none', width: '100px', fontSize: '13px' },
  delTag: { border: 'none', background: 'none', padding: '0 8px', cursor: 'pointer', color: '#999', borderLeft: '1px solid #eee' },
  addBtn: { border: '1px dashed #ee4d2d', background: '#fff', color: '#ee4d2d', padding: '6px 15px', cursor: 'pointer', borderRadius: '2px' },
  // Removido tableLayout: fixed para permitir ajuste dinâmico
  table: { width: '100%', borderCollapse: 'collapse', marginTop: '20px' }, 
  trHead: { background: '#f6f6f6' },
  th: { padding: '12px', textAlign: 'left', fontSize: '13px', border: '1px solid #e8e8e8' },
  tr: { border: '1px solid #e8e8e8' },
  td: { padding: '10px', border: '1px solid #e8e8e8', verticalAlign: 'middle' },
  // Adicionado boxSizing para garantir que o input não expanda a célula
  tableInput: { width: '100%', padding: '8px', border: '1px solid #dcdcdc', borderRadius: '2px', outline: 'none', textAlign: 'center', boxSizing: 'border-box' },
  footer: { padding: '15px 20px', borderTop: '1px solid #e8e8e8', display: 'flex', justifyContent: 'flex-end' }
};